name: simple-data-exchanger

services:
  postgres:
    image: "postgres:14.4"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
    expose:
      - "5432"
    networks:
      - sde-net

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      DB_SCHEMA: public
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
    command:
      - start-dev
      - --import-realm
    volumes:
      # Mount path can be customized according to the project folder structure
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - "4011:8080"
    depends_on:
      - postgres
    networks:
      - sde-net

  edc-server-mock:
    image: wiremock/wiremock:3.2.0
    ports:
      - 3002:8080
    volumes:
      - ./wiremock/edc:/home/wiremock
  partner-pool-mock:
    image: wiremock/wiremock:3.2.0
    ports:
      - 3001:8080
    volumes:
      - ./wiremock/partner_pool:/home/wiremock
  digital-twins-mock:
    image: wiremock/wiremock:3.2.0
    ports:
      - 3003:8080
    volumes:
      - ./wiremock/digital_twins:/home/wiremock
  bpn-discovery-mock:
    image: wiremock/wiremock:3.2.0
    ports:
      - 3004:8080
    volumes:
      - ./wiremock/bpn_discovery:/home/wiremock

networks:
  sde-net:

volumes:
  postgres-data: